### ISSUE TITLE
java.lang.NumberFormatException: null at me.potic.articles.service.ArticlesService.upsertFromPocket

### ISSUE THREAD

**Issue by yermilov** [potic/potic-articles#17]
`22:26:05.145 [http-nio-8080-exec-10] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: request for /user/59d414b2f9171b129c803fa3/article/fromPocket failed: upserting article for user 59d414b2f9171b129c803fa3 failed: null] with root cause
java.lang.NumberFormatException: null
        at java.lang.Long.parseLong(Long.java:552)
        at java.lang.Long.parseLong(Long.java:631)
        at java_lang_Long$parseLong.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at java_lang_Long$parseLong.call(Unknown Source)
        at me.potic.articles.service.ArticlesService.upsertFromPocket(ArticlesService.groovy:98)
`

**Comment by yermilov** [comment]
`22:45:22.321 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: POST request for /user/59d414b2f9171b129c803fa3/article/fromPocket; BODY=[item_id:910264316, status:2] failed: upserting article [item_id:910264316, status:2] for user 59d414b2f9171b129c803fa3 failed: null] with root cause
java.lang.NumberFormatException: null`

**Comment by yermilov** [comment]
`22:45:52.812 [http-nio-8080-exec-10] INFO  m.p.articles.service.ArticlesService - upserting article [is_article:1, image:[item_id:1936222415, src:http://img.pravda.com/images/doc/b/c/bc8b171-----------------2015----.jpg, height:0, width:0], amp_url:http://www.pravda.com.ua/articles/2017/10/24/7159544/index.amp, excerpt:За часів екс-президента Віктора Януковича і після Майдану наші суди бачили багато: і підозрюваних у ковдрах, і карети "швидкої", і жорсткі дії правоохоронців., word_count:1189, images:[1:[src:http://img.pravda.com/images/doc/b/c/bc8b171-----------------2015----.jpg, credit:, height:0, image_id:1, item_id:1936222415, caption:Микола Коханівський, width:0], 3:[src:http://img.pravda.com/images/doc/6/7/6702444------.jpg, credit:, height:0, image_id:3, item_id:1936222415, caption:, width:0], 2:[src:http://img.pravda.com/images/doc/1/2/1230376--------.png, credit:, height:0, image_id:2, item_id:1936222415, caption:Руслан Кочмала, width:0]], has_video:0, time_added:1508882746, status:0, sort_id:0, resolved_url:http://www.pravda.com.ua/articles/2017/10/24/7159544/, item_id:1936222415, resolved_id:1936186948, given_url:https://l.facebook.com/l.php?u=http%3A%2F%2Fwww.pravda.com.ua%2Farticles%2F2017%2F10%2F24%2F7159544%2F&h=ATPge0duL8IJY2z4jzzjjYd4wdN9u9DgPpg3cSs1LoUk5iPjnHtpu6QHYK2ybKbmXIFoVCRnqqBn276j1J0-SnuB1dTCAy3c_18wl_4yT5okmr4VxXYnHTkqIFAtZ6hcB7xIXcB6OkBYrpflgm1Xdydv4Sf1nSukvcXZ8O4iEpz1jFEcnBLlujsFSOe4PX5wmgDuJT4b_g-BquaU2i65Fp5AkhD1gJLYK3TK9eaFFbjpBpyY1Jm9NwQ3EUoRqIQX7Qv5bsQy82aDiuzHIqZx1WPT0FAA83JCb18, resolved_title:Барикада у суді, штурм та поруки. Як розглядали справу Коханівського, is_index:0, time_updated:1508882747, time_favorited:0, time_read:0, favorite:0, given_title:https://l.facebook.com/l.php?u=http://www.pravda.com.ua/articles/2017/10/24, has_image:1] for user 59d41453f9171b129c803fa2`
